apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  name: jvb-udp
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - name: "30300"
    port: 30300
    protocol: UDP
    targetPort: 30300
    nodePort: 30300
  - name: "4443"
    port: 4443
    targetPort: 4443   
  selector:
    k8s-app: jvb